version: '3.8'

services:
  backend:
    build: 
      context: ./API
    container_name: crmTourist_backend
    ports:
      - "5001:5000"  # Внешний порт 5001 -> Внутренний 5000
    env_file:
      - ./API/.env
    volumes:
      - ./API/uploads:/app/uploads
    depends_on:
      - db

  frontend:
    build:
      context: ./front
    container_name: crmTourist_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: crmTourist_db
    ports:
        - "5433:5432"
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PWD:-postgres}
      - POSTGRES_DB=${DB_NAME:-postgres}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
