# Сборка приложения
FROM node:18 AS build

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Сервер для статических файлов
FROM nginx:alpine

# Открываем порт для приложения
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
