# Используем Node.js LTS версию
FROM node:18

# Устанавливаем рабочую директорию внутри контейнера
WORKDIR /app

# Копируем package.json и package-lock.json для установки зависимостей
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install --production

# Копируем остальные файлы в контейнер
COPY . .

# Открываем порт (замени на свой, если другой)
EXPOSE 5000

# Запускаем приложение
CMD ["node", "app.js"]
